### ISSUE TITLE
Support for fetching playlists

### ISSUE THREAD

**Issue by prajapati-parth** [jworley/gatsby-source-youtube#3]
Do we have support to fetch playlist data from youtube's channel?

**Comment by cedricdelpoux** [comment]
I'm interested too. Any plans to support this? Are you open to PR?

**Comment by cedricdelpoux** [comment]
Hi @prajapati-parth , this repository is outdated. 
Please checkout the new version [v2.0.0](https://github.com/cedricdelpoux/gatsby-source-youtube)
It support playlists natively. You even don't have to pass any option because the new plugin use an OAuth 2.0 token so we can query your playlists by default
